### ISSUE TITLE
Unable to fetch data for user: 0

### ISSUE THREAD

**Issue by gunr2171** [SO-Close-Vote-Reviewers/SOCVR-Chatbot#146]
```
@Pham add 0 to reviewer

0: Unable to fetch data for user: 0
----
at ChatExchangeDotNet.User..ctor(RoomMetaInfo meta, Int32 userID, String cookieKey)
at ChatExchangeDotNet.Room.GetUser(Int32 userID)
at SOCVR.Chatbot.ChatbotActions.Commands.Permission.AddUserToGroup.RunAction(Message incomingChatMessage, Room chatRoom) in C:\Users\Samuel\Documents\GitHub\SOCVR-Chatbot\source\SOCVR.Chatbot\ChatbotActions\Commands\Permission\AddUserToGroup.cs:line 75
```

**Comment by gunr2171** [comment]
This actually seems to be an error coming from SE.Net, so we need to add a check to see if that user exists before assuming we have the parsed value.
